### ISSUE TITLE
 [10.0] sale_triple_discount: broken by https://github.com/OCA/account-invoicing/pull/500 (at least travis is red)

### ISSUE THREAD

**Issue by lmignon** [OCA/sale-workflow#817]
https://github.com/OCA/account-invoicing/pull/500 
https://travis-ci.org/OCA/sale-workflow/builds/501135521
If I revert the changes introduced into https://github.com/OCA/account-invoicing/pull/500 the tests no more fails on `sale_triple_discount`

**Comment by SimoRubi** [comment]
I'm looking into it, this is one of those funny errors that disappear when you are debugging them.. :imp:

**Comment by lmignon** [comment]
@SimoRubi This error makes all PR :red_circle: :unamused:

**Comment by SimoRubi** [comment]
@lmignon I found out that there is an easy fix: you can use `self.so_line2.discount = 50.0` instead of `self.so_line2.discount3 = 50.0` in the failing test, then everything should be :heavy_check_mark: back again.

Anyway that wouldn't help at all with the root cause, that is what I'm trying to find.

If there is any hurry to have the tests working, that solution is the fastest.

**Comment by lmignon** [comment]
@SimoRubi I don't use `sale_triple_discount`.  This addon is broken by your changes.  The problem is that all the PR are now :red_circle: on the sale-workflow and therefore nor mergeable. Can you provide the right fix. I don't want and have no budget to dig into an addon I didn't use.

**Comment by SimoRubi** [comment]
@lmignon please check if https://github.com/OCA/account-invoicing/pull/517 fixes this issue, thanks

**Comment by rafaelbn** [comment]
Hi this is fixed https://github.com/OCA/sale-workflow/pull/927

**Comment by rafaelbn** [comment]
Please if you consider solved, close it :smile:

**Comment by SimoRubi** [comment]
@rafaelbn in the PR you tagged, travis is still failing some builds:
![image](https://user-images.githubusercontent.com/32064796/65490747-fdc89400-dead-11e9-97d7-46c13ed53fd3.png)
This will be solved when travis is green

**Comment by rousseldenis** [comment]
@rafaelbn At least when a maintainer merges failing PR, is to ensure that action are made to restablish main branch to green. Do you have open an issue for that ?

**Comment by pedrobaeza** [comment]
The mentioned PR (#927) is correct, but not enough. Without it, there isn't the possibility of knowing what is the problem. The same problem would arise if we have done the PG version patch through a bot. Then, it's the duty of the module maintainers/authors to fix the broken tests IMO.

**Comment by SimoRubi** [comment]
There are a couple of open PRs that would fix this issue: https://github.com/OCA/account-invoicing/pull/517 and https://github.com/OCA/account-invoicing/pull/525.
Each of them has its own reasons to be merged/not merged

**Comment by rafaelbn** [comment]
Please @mreficent could you give us you point of view about this issue with travis in sale-workflow and the 2 PRs proposed to be fixed? We need to have this branch green :cry:  Thank you!

**Comment by eLBati** [comment]
It seems everyone agrees on the fact that both https://github.com/OCA/account-invoicing/pull/525 and https://github.com/OCA/account-invoicing/pull/517 are workarounds and we should investigate the real odoo bug.

Meanwhile, we should merge one of them.

I would go with https://github.com/OCA/account-invoicing/pull/525 since it has more approvals.

**Comment by SimoRubi** [comment]
@OCA/accounting-maintainers any news about PRs https://github.com/OCA/account-invoicing/pull/517 or https://github.com/OCA/account-invoicing/pull/525?

**Comment by pedrobaeza** [comment]
Merging is on the way, so closing
